version: '3.8'
services:
  my-bank:
    build: .
    image: my-bank
    container_name: my-bank
    ports:
      - "8080:8080"
    depends_on:
      - bank-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bank-db:5432/bank

  bank-db:
    image: postgres:14-alpine
    container_name: bank-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot